version: '3.9'

services:

  naming-server:
    build: ./naming-server
    container_name: naming-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  currency-report:
    build: ./currency-report
    container_name: currency-report
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    ports:
      - "8100:8100"
    networks:
      - microservices-net

  currency-history:
    build: ./currency-history
    container_name: currency-history
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    ports:
      - "8101:8101"
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - naming-server
      - currency-report
      - currency-history
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
